name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag, or SHA to build
        default: master
        required: false
        type: string
      macos-arm64:
        description: Build for macOS Arm64
        default: true
        required: false
        type: boolean
      macos-intel:
        description: Build for macOS Intel
        default: true
        required: false
        type: boolean
      windows:
        description: Build for Windows
        default: true
        required: false
        type: boolean
      deb:
        description: Build .deb for Debian / Ubuntu
        default: true
        required: false
        type: boolean
      rpm:
        description: Build .rpm for Fedora
        default: true
        required: false
        type: boolean
      tgz:
        description: Build .tar.gz for Linux
        default: true
        required: false
        type: boolean

jobs:
  macos-arm64:
    name: Build for macOS Arm64
    runs-on: macos-latest
    if: ${{ inputs.macos-arm64 }}

    steps:
      - name: Create case-sensitive directory
        run: |
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 4g -volname workspace /tmp/workspace.sparseimage
          sudo hdiutil attach -notremovable -nobrowse -mountpoint /tmp/workspace /tmp/workspace.sparseimage

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash macos_brew_setup.txt

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash bootStrapMacOS_Monterey.arm64.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: /tmp/workspace/avidemux2/installer/*.dmg

  macos-intel:
    name: Build for macOS Intel
    runs-on: macos-latest
    if: ${{ inputs.macos-intel }}

    steps:
      - name: Create case-sensitive directory
        run: |
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 4g -volname workspace /tmp/workspace.sparseimage
          sudo hdiutil attach -notremovable -nobrowse -mountpoint /tmp/workspace /tmp/workspace.sparseimage

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash macos_brew_setup.txt

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          export MACOSX_DEPLOYMENT_TARGET=$(xcrun --sdk macosx --show-sdk-version)
          bash bootStrapOsx_Catalina.bash --enable-qt6

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel
          path: /tmp/workspace/avidemux2/installer/*.dmg

  windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    if: ${{ inputs.windows }}

    steps:
      - name: Create tmp directory
        run: |
          mkdir -p /tmp/workspace

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash createDebFromSourceUbuntu.bash --deps-only

      - name: Install MXE
        working-directory: /tmp/workspace
        run: |
          sudo apt-get install \
            autoconf \
            automake \
            autopoint \
            bash \
            bison \
            bzip2 \
            flex \
            g++ \
            g++-multilib \
            gettext \
            git \
            gperf \
            intltool \
            libc6-dev-i386 \
            libgdk-pixbuf2.0-dev \
            libltdl-dev \
            libgl-dev \
            libpcre3-dev \
            libssl-dev \
            libtool-bin \
            libxml-parser-perl \
            lzip \
            make \
            openssl \
            p7zip-full \
            patch \
            perl \
            python3 \
            python3-setuptools \
            python3-mako \
            python3-packaging \
            python3-pkg-resources \
            python3-setuptools \
            python-is-python3 \
            ruby \
            sed \
            sqlite3 \
            unzip \
            wget \
            xz-utils \
            g++-multilib \
            libc6-dev-i386
          bash avidemux2/mxe/mxe-setup.sh

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash bootStrapCrossMingwQt6_mxe.sh --mxe-root=/tmp/workspace/mxe
          ls installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: /tmp/workspace/avidemux2/installer/*

  deb:
    name: Build .deb for Debian / Ubuntu
    runs-on: ubuntu-latest
    if: ${{ inputs.deb }}

    steps:
      - name: Create tmp directory
        run: |
          mkdir -p /tmp/workspace

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash createDebFromSourceUbuntu.bash --deps-only

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash bootStrap.bash --deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: /tmp/workspace/avidemux2/pkgs/*

  rpm:
    name: Build .rpm for Fedora
    runs-on: ubuntu-latest
    if: ${{ inputs.rpm }}

    steps:
      - name: Create tmp directory
        run: |
          mkdir -p /tmp/workspace

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash createDebFromSourceUbuntu.bash --deps-only

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash bootStrap.bash --rpm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: /tmp/workspace/avidemux2/pkgs/*

  tgz:
    name: Build .tar.gz for Linux
    runs-on: ubuntu-latest
    if: ${{ inputs.tgz }}

    steps:
      - name: Create tmp directory
        run: |
          mkdir -p /tmp/workspace

      - name: Clone repositories
        working-directory: /tmp/workspace
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }}.git build
          mkdir avidemux2
          pushd avidemux2
          git init
          git remote add origin https://github.com/mean00/avidemux2.git
          git fetch --depth 1 origin ${{ inputs.ref }}
          git checkout FETCH_HEAD
          git submodule update --init --recursive --depth 1
          popd

      - name: Apply patch
        working-directory: /tmp/workspace/avidemux2
        run: |
          git apply ../build/avidemux2.patch

      - name: Install dependencies
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash createDebFromSourceUbuntu.bash --deps-only

      - name: Build
        working-directory: /tmp/workspace/avidemux2
        run: |
          bash bootStrap.bash --tgz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tgz
          path: /tmp/workspace/avidemux2/pkgs/*
