name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag, or SHA to build
        default: master
        required: false
        type: string
      macos-arm64:
        description: Build macOS Arm64
        default: true
        required: false
        type: boolean

jobs:
  macos-arm64:
    name: Build macOS Arm64
    runs-on: macos-latest
    if: ${{ inputs.macos-arm64 }}

    steps:
      - name: Create case-sensitive directory
        run: |
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 4g -volname workspace /tmp/workspace.sparseimage
          sudo hdiutil attach -notremovable -nobrowse -mountpoint /tmp/workspace /tmp/workspace.sparseimage

      - name: Clone repositories
        run: |
          cd /tmp/workspace
          git clone https://github.com/${{ github.repository }}.git build
          git clone https://github.com/mean00/avidemux2.git

      - name: Apply patch
        run: |
          cd /tmp/workspace/avidemux2
          git apply ../build/macos-arm64.patch

      - name: Build
        run: |
          cd /tmp/workspace/avidemux2
          bash bootStrapMacOS_Monterey.arm64.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: /tmp/workspace/avidemux2/*.app
          include-hidden-files: true
