name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag, or SHA to build
        default: master
        required: false
        type: string
      macos-arm64:
        description: Build macOS Arm64
        default: true
        required: false
        type: boolean

jobs:
  macos-arm64:
    name: Build macOS Arm64
    runs-on: macos-latest
    if: ${{ inputs.macos-arm64 }}

    steps:
      - name: Create case-sensitive directory
        run: |
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 4g -volname workspace /tmp/workspace.dmg
          sudo hdiutil attach -notremovable -nobrowse -mountpoint /Volumes/workspace /tmp/workspace

      - name: Checkout build-avidemux2
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          path: /Volumes/workspace

      - name: Checkout avidemux2
        uses: actions/checkout@v4
        with:
          repository: mean00/avidemux2
          ref: ${{ inputs.ref }}
          path: /Volumes/workspace
          submodules: true

      - name: Apply patch
        run: |
          git apply ../build-avidemux2/macos-arm64.patch

      - name: Build
        run: bash bootStrapMacOS_Monterey.arm64.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: /Volumes/workspace/avidemux2/Avidemux2.8.app
